### ISSUE TITLE
Δημιουργία Splash Activity

### ISSUE THREAD

**Issue by KomnisEvangelos** [KomnisEvangelos/GeoApp#42]
Δημιουργία Splash Activity με την εμφάνιση του Logo εφαρμογής.

Η συγκεκριμένη οθόνη να περιέχει επίπεδο progress bar και αναφορά στο Porject με "TM © 2023 Geo App Project - All Rights Reserved."

**Comment by nefeliverg** [comment]
!!!!!!!!!!!!!!!!

Στις Σάβ 2 Δεκ 2023 στις 1:41 μ.μ., ο/η Evangelos Komnis <
***@***.***> έγραψε:

**Comment by nefeliverg** [comment]
nefelh bergidou
