### ISSUE TITLE
Τα στοιχεία των χρηστών δεν υπάρχουν στην βάση, και επομένως δεν μπορούν να ανακτηθούν και να εμφανιστούν

### ISSUE THREAD

**Issue by StylianiMakri** [KomnisEvangelos/GeoApp#57]
Θα πρέπει  τα στοιχεία που συμπληρώνει ο χρήστης κατά της εγγραφή του στην εφαρμογή να αποθηκεύονται στην βάση, και όχι τοπικά στην εφαρμογή με getters/setters.

**Comment by KomnisEvangelos** [comment]
Μήπως έχει επιλυθεί αυτο;
